name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        libboost-dev \
        libgtest-dev

    - name: Install Eigen 3.4
      run: |
        git clone --branch 3.4.0 https://gitlab.com/libeigen/eigen.git ${{ github.workspace }}/deps/eigen
        cmake \
          -S ${{ github.workspace }}/deps/eigen \
          -B ${{ github.workspace }}/deps/eigen/build
        cmake --build ${{ github.workspace }}/deps/eigen/build
        sudo cmake --install ${{ github.workspace }}/deps/eigen/build

    - name: Install autodiff
      run: |
        git clone --branch v0.6.8 https://github.com/autodiff/autodiff.git ${{ github.workspace }}/deps/autodiff
        cmake                                                  \
          -S ${{ github.workspace }}/deps/autodiff             \
          -B ${{ github.workspace }}/deps/autodiff/build       \
          -DAUTODIFF_BUILD_EXAMPLES=OFF                        \
          -DAUTODIFF_BUILD_TESTS=OFF                           \
          -DAUTODIFF_BUILD_PYTHON=OFF
        cmake --build ${{ github.workspace }}/deps/autodiff/build
        sudo cmake --install ${{ github.workspace }}/deps/autodiff/build

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build          \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}     \
        -DBUILD_TESTS=ON                                \
        -DBUILD_EXAMPLES=ON

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make -j2

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: make test

  codecov:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        lcov \
        libboost-dev \
        libgtest-dev

    - name: Install Eigen 3.4
      run: |
        git clone --branch 3.4.0 https://gitlab.com/libeigen/eigen.git ${{ github.workspace }}/deps/eigen
        cmake \
          -S ${{ github.workspace }}/deps/eigen \
          -B ${{ github.workspace }}/deps/eigen/build
        cmake --build ${{ github.workspace }}/deps/eigen/build
        sudo cmake --install ${{ github.workspace }}/deps/eigen/build

    - name: Install autodiff
      run: |
        git clone --branch v0.6.8 https://github.com/autodiff/autodiff.git ${{ github.workspace }}/deps/autodiff
        cmake \
          -S ${{ github.workspace }}/deps/autodiff \
          -B ${{ github.workspace }}/deps/autodiff/build \
          -DAUTODIFF_BUILD_EXAMPLES=OFF \
          -DAUTODIFF_BUILD_TESTS=OFF \
          -DAUTODIFF_BUILD_PYTHON=OFF
        cmake --build ${{ github.workspace }}/deps/autodiff/build
        sudo cmake --install ${{ github.workspace }}/deps/autodiff/build

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build            \
        -DCMAKE_BUILD_TYPE=Debug                          \
        -DCMAKE_CXX_FLAGS="-O0 -g --coverage -fno-inline" \
        -DCMAKE_EXE_LINKER_FLAGS="--coverage"             \
        -DBUILD_TESTS=ON                                  \
        -DBUILD_EXAMPLES=OFF

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make -j2

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: make test

    - name: Analyze coverage
      working-directory: ${{ github.workspace }}
      run: |
        lcov -c --no-external --directory include -d build/tests/CMakeFiles -o coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info -t ${{ secrets.CODECOV_TOKEN }}
